### ISSUE TITLE
[Assignment] 1차 세미나 과제

### ISSUE THREAD

**Issue by hansh0101** [KINGSAMJO/iOS_Seunghyeon#1]
## 📌  Feature Issue

1차 세미나 과제: 필수과제, 성장과제, 도전과제

## 📝  To-do

- [x] 필수과제 1. 로그인 페이지 만들기
- [x] 필수과제 2. 회원가입 페이지 만들기
- [x] 필수과제 3. 자기소개 페이지 만들기
- [x] 성장과제 1. 화면 이동 + @
- [x] 성장과제 2. 사진 비율 조정 및 스크롤 추가
- [x] 도전과제 1. DataBinding
- [x] 도전과제 2. MVVM
