### ISSUE TITLE
[Assignment] 2차 세미나 과제

### ISSUE THREAD

**Issue by hansh0101** [KINGSAMJO/iOS_Seunghyeon#3]
## 📌  Feature Issue

2차 세미나 과제: 필수과제, 성장과제, 도전과제

## 📝  To-do

- [x] 필수과제 1. FollowerRecyclerView와 RepositoryRecyclerView를 가지는 FollowerFragment와 RepositoryFragment 만들기
- [x] 성장과제 1. RecyclerView itemView 클릭 이벤트 구현하기
- [x] 성장과제 2. ItemDecoration을 활용해 item 간 간격 및 구분선 설정하기
- [x] 성장과제 3. RecyclerView item 이동, 삭제 구현하기
- [x] 도전과제 1. Fragment 보일러 플레이트 코드 개선하기
- [x] 도전과제 2. notifyDataSetChanged의 문제점 개선하기
