### ISSUE TITLE
[Assignment] 3차 세미나 과제

### ISSUE THREAD

**Issue by hansh0101** [KINGSAMJO/iOS_Seunghyeon#5]
## 📌  Feature Issue

3차 세미나 과제: 필수과제, 성장과제, 도전과제

## 📝  To-do

- [x] 필수과제 1. 폰트 적용하기
- [x] 필수과제 2. ProfileFragment 구현하기
- [x] 필수과제 3. HomeFragment 구현하기
- [x] 성장과제 1. ViewPager 중첩 스크롤 문제 해결하기
- [x] 도전과제 1. 갤러리에서 받아온 이미지 Uri를 Glide를 이용해 화면에 띄워보기
