### ISSUE TITLE
[Assignment] 4차 세미나 과제

### ISSUE THREAD

**Issue by hansh0101** [KINGSAMJO/iOS_Seunghyeon#7]
## 📌  Feature Issue

4차 세미나 과제: 필수과제, 성장과제, 도전과제

## 📝  To-do

- [x] 필수과제 1. 로그인, 회원가입 API 연동
- [x] 성장과제 1. Github API 연동
- [x] 성장과제 2. Wrapper 클래스 구현
- [x] 도전과제 1. (RxKotlin, )Coroutine 사용한 비동기 처리 구현
