### ISSUE TITLE
[Assignment] 7차 세미나 과제

### ISSUE THREAD

**Issue by hansh0101** [KINGSAMJO/iOS_Seunghyeon#9]
## 📌  Feature Issue

7차 세미나 과제: 필수과제, 성장과제, 도전과제

## 📝  To-do

- [x] 필수과제 1. SharedPreferences를 사용한 자동로그인 / 자동로그인 해제 구현
- [x] 성장과제 1. Navigation Component를 사용한 온보딩 화면 만들기
- [x] 도전과제 1. Room을 사용한 자동로그인 로직 만들기
